{
 "title": "KCP / Kyma Environment Broker / Subaccount Sync",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "error_category",
    "query": {
     "query": "label_values({__name__=~\"kcp_keb_provisioning_result|kcp_keb_deprovisioning_result\", plan_id=~\"$plan_id\"}, error_category)"
    }
   },
   {
    "name": "error_reason",
    "query": {
     "query": "label_values({__name__=~\"kcp_keb_provisioning_result|kcp_keb_deprovisioning_result\", plan_id=~\"$plan_id\", error_category=~\"$error_category\"}, error_reason)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Broker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration [s]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_gc_duration_seconds{service=\"subaccount-sync\"})",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_goroutines{service=\"subaccount-sync\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Gothreads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_threads{service=\"subaccount-sync\"})",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (go_memstats_alloc_bytes{service=\"subaccount-sync\"})",
       "legendFormat": "bytes allocated"
      },
      {
       "expr": "avg by (service) (rate(go_memstats_alloc_bytes_total{service=\"subaccount-sync\"}[1m]))",
       "legendFormat": "alloc rate"
      },
      {
       "expr": "sum by (service) (go_memstats_stack_inuse_bytes{service=\"subaccount-sync\"})",
       "legendFormat": "stack inuse"
      },
      {
       "expr": "sum by (service) (go_memstats_heap_inuse_bytes{service=\"subaccount-sync\"})",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service) (process_open_fds{service=\"subaccount-sync\"})",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "DB connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (service) (go_sql_stats_connections_idle{service=\"subaccount-sync\"})",
       "legendFormat": "Idle"
      },
      {
       "expr": "avg by (service) (go_sql_stats_connections_max_open{service=\"subaccount-sync\"})",
       "legendFormat": "Max open"
      },
      {
       "expr": "avg by (service) (go_sql_stats_connections_in_use{service=\"subaccount-sync\"})",
       "legendFormat": "In use"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container) (container_memory_usage_bytes{job=\"kubelet\",pod=~\"subaccount-sync.*\",container!=\"POD\",container!=\"\"})",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{pod=~\"subaccount-sync.*\"})",
     "legendFormat": "{{container}} - Requests"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{pod=~\"subaccount-sync.*\"})",
     "legendFormat": "{{container}} - Limit"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\",pod=~\"subaccount-sync.*\",container!=\"POD\",container!=\"\"}[1m]))",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{pod=~\"subaccount-sync.*\"})",
     "legendFormat": "{{container}} - Requests"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_cpu_cores{pod=~\"subaccount-sync.*\"})",
     "legendFormat": "{{container}} - Limit"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (rate(container_network_receive_bytes_total{pod=~\"subaccount-sync.*\"}[1m])))",
     "legendFormat": "subaccount-sync"
    }
   ]
  }
 ]
}