version: "2"

run:
  allow-parallel-runners: true
  timeout: 2m
  
output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
      
linters:
  default: none
  enable:
    - errcheck
    - govet
  exclusions:
    presets:
      - common-false-positives
    rules:
      # Exclude errcheck for defer Close() calls which are common and usually safe to ignore
      - linters:
          - errcheck
        text: "Error return value of.*Close.*is not checked"
      # Exclude errcheck for common os operations that are often safe to ignore
      - linters:
          - errcheck
        text: "Error return value of.*os\\.(Remove|RemoveAll|Setenv|Unsetenv).*is not checked"

formatters:
  enable:
    - goimports
    - gofmt