version: "2"

run:
  allow-parallel-runners: true
  timeout: 2m
  
output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
      
linters:
  default: none
  enable:
    - errcheck
    - goimports
    - govet
    - gofmt