version: "2"

run:
  allow-parallel-runners: true
  timeout: 2m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - errcheck    # Check for unchecked errors
    - govet       # Go's built-in static analyzer
    - bodyclose   # Check whether HTTP response bodies are closed
    - misspell    # Detect commonly misspelled words
    - goconst     # Find repeated strings that could be replaced by a constant
    - unconvert   # Detect redundant type conversions
    - unused      # Detect unused constants, variables, functions and types
    - cyclop      # Check code complexity
    - staticcheck # Check set of rules from staticcheck
  settings:
    unused:
      field-writes-are-uses: false # Mark all struct fields that have been written to as used.
    cyclop:
      max-complexity: 30
    staticcheck:
      checks:
        - "all"
        - "-QF1008" # Omit embedded fields from selector expression.
        - "-ST1000" # Incorrect or missing package comment.
        - "-ST1005" # Incorrectly formatted error string.
        - "-ST1003" # Poorly chosen identifier.
formatters:
  enable:
    - goimports
    - gofmt