run:
  allow-parallel-runners: true
  timeout: 5m

output:
  formats:
    - format: colored-line-number

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude test files from noisy style linters
    - path: _test\.go
      linters:
        - gosec         # Security checks less relevant in tests
    
    # Exclude e2e and test utilities from unused checks  
    - path: (e2e|_test\.go|test_|suite_test\.go)
      linters:
        - unused        # Test utilities may be used in future/other tests
    
    # Specific gosec exclusions
    - linters:
        - gosec
      text: "G115"      # Integer overflow conversions (mostly false positives)
    - linters:
        - gosec  
      text: "G306"      # File permissions in tests are acceptable

linters:
  disable-all: true
  enable:
    # Original linters
    - errcheck      # Checks for unchecked errors
    - goimports     # Checks import formatting
    - govet         # Go vet checks (printf, struct tags, etc)
    - gofmt         # Checks code formatting
    
    # Code quality & bugs
    - staticcheck   # Comprehensive static analysis
    - typecheck     # Type checks the Go code
    
    # Performance & resources
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds HTTP requests without context
    
    # Security (critical only)
    - gosec         # Security-focused checks

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
    
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
    
  staticcheck:
    checks: ["all"]
    
  gosimple:
    checks: ["all"]
    
  unused:
    check-exported: false
    
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G101  # Look for hard coded credentials
      - G104  # Audit errors not checked (covered by errcheck)
      - G402  # TLS MinVersion too low (may need for compatibility)
      - G404  # Use of weak random number generator
      
  goconst:
    min-len: 3
    min-occurrences: 3
    
  misspell:
    locale: US
    
  whitespace:
    multi-if: false
    multi-func: false