run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  build-tags:
    - integration
    - e2e

linters:
  disable-all: true
  enable:
    - errcheck    # Critical: unchecked errors can cause silent failures
    - govet       # Critical: detects suspicious constructs and correctness issues
    - typecheck   # Critical: ensures type safety

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Start lenient, can tighten later
  govet:
    check-shadowing: false  # Start with core checks only
    enable:
      - nilness
      - unusedresult
      - unusedwrite

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Allow unchecked errors for logging calls - common pattern
    - text: "Error return value of `.*\\.Log` is not checked"
      linters:
        - errcheck
    # Allow unchecked errors for fmt.Print* calls in tests/debug  
    - text: "Error return value of `fmt\\."
      linters:
        - errcheck