module-name: kyma-environment-broker
<<<<<<< HEAD
rc-tag: 1.10.22
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environments-cleanup-job:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-archiver-job:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-expirator-job:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-sync:1.10.22
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker-globalaccounts:1.10.22
=======
rc-tag: 1.10.6
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:1.10.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:1.10.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environments-cleanup-job:1.10.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:1.10.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-archiver-job:1.10.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-expirator-job:1.10.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:1.10.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-sync:1.10.6
>>>>>>> a32bde9c (Bump sec-scanners-config.yaml, KEB images and Chart to 1.10.6 (#1181))
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
    - "testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
