module-name: kyma-environment-broker
rc-tag: 0.0.111111
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:0.0.111111
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:0.0.111111
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environments-cleanup-job:0.0.111111
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:0.0.111111
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-archiver-job:0.0.111111
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-expirator-job:0.0.111111
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:0.0.111111
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-sync:0.0.111111
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
    - "testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
