// Code generated by mockery v2.14.0. DO NOT EDIT.

package automock

import (
	mock "github.com/stretchr/testify/mock"

	runtime "github.com/kyma-project/kyma-environment-broker/internal/runtime"
)

// OptionalComponentService is an autogenerated mock type for the OptionalComponentService type
type OptionalComponentService struct {
	mock.Mock
}

// AddComponentToDisable provides a mock function with given fields: name, disabler
func (_m *OptionalComponentService) AddComponentToDisable(name string, disabler runtime.ComponentDisabler) {
	_m.Called(name, disabler)
}

type mockConstructorTestingTNewOptionalComponentService interface {
	mock.TestingT
	Cleanup(func())
}

// NewOptionalComponentService creates a new instance of OptionalComponentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOptionalComponentService(t mockConstructorTestingTNewOptionalComponentService) *OptionalComponentService {
	mock := &OptionalComponentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
