global:
  ingress:
    domainName: localhost
  images:
    cloudsql_proxy:
      repository: eu.gcr.io/sap-ti-dx-kyma-mps-dev/images/cloudsql-proxy
      tag: 2.11.3-sap
    container_registry:
      path: europe-docker.pkg.dev/kyma-project/prod
    kyma_environment_broker:
      dir:
      version: "1.19.3"
    kyma_environment_broker_schema_migrator:
      dir:
      version: 1.19.3
    kyma_environments_subaccount_cleanup_job:
      dir:
      version: "1.19.3"
    kyma_environment_trial_cleanup_job:
      dir:
      version: "1.19.3"
    kyma_environment_expirator_job:
      dir:
      version: "1.19.3"
    kyma_environment_deprovision_retrigger_job:
      dir:
      version: "1.19.3"
    kyma_environment_runtime_reconciler:
      dir:
      version: "1.19.3"
    kyma_environment_subaccount_sync:
      dir:
      version: "1.19.3"
    kyma_environment_globalaccounts:
      dir:
      version: "1.19.3"
    kyma_environment_service_binding_cleanup_job:
      dir:
      version: 1.19.3
      
  kyma_environment_broker:
    serviceAccountName: "kcp-kyma-environment-broker"
  istio:
    gateway: "kyma-system/kyma-gateway"
    proxy:
      port: 15020
  database:
    cloudsqlproxy:
      enabled: false
      workloadIdentity:
        enabled: false
    embedded:
      enabled: true
    # Values for GCP managed PostgreSQL database
    managedGCP:
      # secret with a secret key used to encrypt particular data
      encryptionSecretName: "kcp-storage-client-secret"
      instanceConnectionName: ""

  secrets:
    enabled: true
    mechanism: vso
    vso:
      namespace: kyma
      refreshAfter: 30s
      mount: kcp-dev

# Please read the documentation at:
# https://pages.github.tools.sap/kyma/docusaurus-docs/kyma/cicd/argocd/secrets
vsoSecrets:
  secrets:
    edp:
      path: edp
      secretName: "{{ .Values.edp.secretName }}"
      restartTargets:
        - kind: Deployment
          name: >-
            {{- template "kyma-env-broker.fullname" . -}}
      labels: >-
        {{ template "kyma-env-broker.labels" . }}
      templating:
        enabled: true
        keys:
          secret: keb_edp_secret
        data:
          secret: {}
    cis-v1:
      path: cis
      secretName: "{{ .Values.cis.v1.secretName | required \"please specify .Values.cis.v1.secretName\"}}"
      labels: >-
        {{ template "kyma-env-broker.labels" . }}
      templating:
        enabled: true
        keys:
          id: v1_id
          secret: v1_secret
        data:
          id: {}
          secret: {}
    cis-v2:
      path: cis
      secretName: "{{ .Values.cis.v2.secretName | required \"please specify .Values.cis.v2.secretName\"}}"
      restartTargets:
        - kind: Deployment
          name: "{{- .Values.subaccountSync.name -}}"
      labels: >-
        {{ template "kyma-env-broker.labels" . }}
      templating:
        enabled: true
        keys:
          id: v2_id
          secret: v2_secret
        data:
          id: {}
          secret: {}
    cis-accounts:
      path: cis
      secretName: "{{ .Values.cis.accounts.secretName | required \"please specify .Values.cis.accounts.secretName\"}}"
      restartTargets:
        - kind: Deployment
          name: "{{- .Values.subaccountSync.name -}}"
      labels: >-
        {{ template "kyma-env-broker.labels" . }}
      templating:
        enabled: true
        keys:
          id: account_id
          secret: account_secret
        data:
          id: {}
          secret: {}

deployment:
  replicaCount: 1
  image:
    pullPolicy: Always
  securityContext:
    runAsUser: 2000
  strategy: { } # Read more: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  nodeSelector: { }

imagePullSecrets: [ ]
namePrefix: "kcp"
nameOverride: "kyma-environment-broker"
fullnameOverride: "kcp-kyma-environment-broker"
host: "kyma-env-broker"
manageSecrets: true
allowUpdateExpiredInstanceWithContext: "false"

broker:
  port: "8080"
  # serving health probes routes on statusPort
  statusPort: "8071"
  defaultRequestRegion: "cf-eu10"
  operationTimeout: "7h"
  profiler:
    memory: false
  events:
    enabled: true
  enableShootAndSeedSameRegion: "false"
  subaccountMovementEnabled: "false"
  updateCustomResourcesLabelsOnAccountMove: "false"
  useAdditionalOIDCSchema: "false"
  disableMachineTypeUpdate: "false"
  monitorAdditionalProperties: false

binding:
  enabled: false
  bindablePlans: "aws"
  expirationSeconds: 600
  maxExpirationSeconds: 7200
  # minExpirationSeconds can't be lower than 600 seconds. Forced by Gardener
  minExpirationSeconds: 600
  maxBindingsCount: 10
  createBindingTimeout: 15s

service:
  type: ClusterIP
  port: 80

swagger:
  virtualService:
    enabled: true

resources:
  { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi

serviceAccount:
  annotations: { }

lifecycleManager:
  disabled: "false"

infrastructureManager:
  kubernetesVersion: "1.16.9"
  defaultShootPurpose: "development"
  # if empty, the Gardener default value is used
  machineImage: ""
  # if empty, the Gardener default value is used
  machineImageVersion: ""
  defaultTrialProvider: "Azure" # Azure, AWS
  multiZoneCluster: "false"
  controlPlaneFailureTolerance: ""
  useSmallerMachineTypes: "false"
  enableIngressFiltering: "false"
  ingressFilteringPlans: "azure,gcp,aws"

stepTimeouts:
  checkRuntimeResourceUpdate: 180m
  checkRuntimeResourceCreate: 60m
  checkRuntimeResourceDeletion: 60m

trialRegionsMapping: |-
  cf-eu10: europe
  cf-us10: us
  cf-ap21: asia

skrOIDCDefaultValues: |-
  clientID: "9bd05ed7-a930-44e6-8c79-e6defeb7dec9"
  issuerURL: "https://kymatest.accounts400.ondemand.com"
  groupsClaim: "groups"
  groupsPrefix: "-"
  signingAlgs: [ "RS256" ]
  usernamePrefix: "-"
  usernameClaim: "sub"

skrDNSProvidersValues: |-
  providers: []

# Following data serves just as a template
sapConvergedCloudPlanRegionMappings: |-
  cf-eu20-staging:
    - eu-de-1
    - eu-de-2
  cf-eu21-staging:
    - eu-de-3
    - eu-de-4
disableSapConvergedCloud: false
disableProcessOperationsInProgress: "false"
enablePlans: "azure,gcp,azure_lite,trial,aws"
hap:
  rule:
    - aws                             # pool: hyperscalerType: aws
    - aws(PR=cf-eu11) -> EU           # pool: hyperscalerType: aws; euAccess: true
    - azure                           # pool: hyperscalerType: azure
    - azure(PR=cf-ch20) -> EU         # pool: hyperscalerType: azure; euAccess: true
    - gcp                             # pool: hyperscalerType: gcp
    - gcp(PR=cf-sa30) -> PR           # pool: hyperscalerType: gcp_cf-sa30
    - trial -> S                      # pool: hyperscalerType: azure; shared: true - TRIAL POOL
    # pool: hyperscalerType: aws; shared: true - TRIAL POOL
    - sap-converged-cloud(HR=*) -> S  # pool: hyperscalerType: openstack_<HYPERSCALER_REGION>; shared: true
    - azure_lite                      # pool: hyperscalerType: azure
    - preview                         # pool: hyperscalerType: aws
    - free                            # pool: hyperscalerType: aws
    # pool: hyperscalerType: azure
onlySingleTrialPerGA: "true"
enableKubeconfigURLLabel: "false"
includeAdditionalParamsInSchema: "false"
showTrialExpirationInfo: "false"
showFreeExpirationInfo: "false"
freeDocsURL: "https://help.sap.com/docs/"
freeExpirationPeriod: 720h
onlyOneFreePerGA: "false"
subaccountsIdsToShowTrialExpirationInfo: "a45be5d8-eddc-4001-91cf-48cc644d571f"
trialDocsURL: "https://help.sap.com/docs/"
useSmallerMachineTypes: "false"

osbUpdateProcessingEnabled: "true"


gardener:
  project: "kyma-dev" # Gardener project connected to SA for HAP credentials lookup
  shootDomain: "kyma-dev.shoot.canary.k8s-hana.ondemand.com"
  kubeconfigPath: "/gardener/kubeconfig/kubeconfig"
  secretName: "gardener-credentials"
  freemiumProviders: "azure,aws"

kubeconfig:
  allowOrigins: "*"

edp:
  authURL: "TBD"
  adminURL: "TBD"
  namespace: "kyma-dev"
  environment: "dev"
  required: false
  disabled: true
  secret: "TBD"
  secretName: "edp-creds"

cis:
  v1:
    authURL: "TBD"
    eventServiceURL: "TBD"
    id: "TBD"
    secret: "TBD"
    secretName: "cis-creds-v1"
  v2:
    authURL: "TBD"
    eventServiceURL: "TBD"
    id: "TBD"
    secret: "TBD"
    secretName: "cis-creds-v2"
    requestInterval: "200ms"
    rateLimitingInterval: "2s"
    maxRequestRetries: "3"
    jobRetries: 6
  accounts:
    authURL: "TBD"
    serviceURL: "TBD"
    id: "TBD"
    secret: "TBD"
    secretName: "cis-creds-accounts"

oidc:
  issuer: https://kymatest.accounts400.ondemand.com
  keysURL: https://kymatest.accounts400.ondemand.com/oauth2/certs
  groups:
    admin: runtimeAdmin
    operator: runtimeOperator
    orchestrations: orchestrationsAdmin
    viewer: runtimeViewer

kebClient:
  scope: "broker:write cld:read"

runtimeAllowedPrincipals: |-
  - cluster.local/ns/kcp-system/sa/kcp-kyma-metrics-collector

subaccountCleanup:
  nameV1: "kcp-subaccount-cleaner-v1.0"
  nameV2: "kcp-subaccount-cleaner-v2.0"
  enabled: "false"
  schedule: "0 1 * * *"

trialCleanup:
  enabled: true
  schedule: "15 1 * * *"
  dryRun: true
  expirationPeriod: 336h
  testRun: false
  testSubaccountID: "prow-keb-trial-suspension"

freeCleanup:
  enabled: true
  schedule: "0,15,30,45 * * * *"
  dryRun: true
  expirationPeriod: 2160h # 90 days
  testRun: false
  testSubaccountID: "prow-keb-trial-suspension"

deprovisionRetrigger:
  schedule: "0 2 * * *"
  dryRun: true
  enabled: true

subaccountSync:
  name: "subaccount-sync"
  enabled: true
  updateResources: false
  alwaysSubaccountFromDatabase: false
  accountSyncInterval: 24h
  storageSyncInterval: 5m
  eventsWindowSize: 20m
  eventsWindowInterval: 15m
  queueSleepInterval: 30s
  metricsPort: 8081
  logLevel: info
  cisRateLimits:
    events:
      rateLimitingInterval: 2s
      maxRequestsPerInterval: 5
    accounts:
      rateLimitingInterval: 2s
      maxRequestsPerInterval: 5

serviceMonitor:
  enabled: false
  scrapeTimeout: &scrapeTimeout 10s
  interval: &scrapeInterval 30s

vmscrapes:
  enabled: true
  scrapeTimeout: *scrapeTimeout
  interval: *scrapeInterval

dashboardConfig:
  landscapeURL: "https://dashboard.dev.kyma.cloud.sap"

runtimeReconciler:
  enabled: false
  dryRun: true
  jobEnabled: false
  jobInterval: 1440
  jobReconciliationDelay: 1s
  metricsPort: 8081

migratorJobs:
  enabled: true
  helmhook:
    enabled: true
    weight: "1"
  argosync:
    enabled: false
    syncwave: "0"

archiving:
  enabled: false
  dryRun: true
cleaning:
  enabled: false
  dryRun: true

metricsv2:
  enabled: false
  operationResultRetentionPeriod: 1h
  operationResultPoolingInterval: 1m
  operationStatsPoolingInterval: 1m
  operationResultFinishedOperationRetentionPeriod: 3h

freemiumWhitelistedGlobalAccountIds: |-
  whitelist:

runtimeConfiguration: |-
  default: |-
    kyma-template: |-
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Kyma
      metadata:
        labels:
          "operator.kyma-project.io/managed-by": "lifecycle-manager"
        name: tbd
        namespace: kcp-system
      spec:
        channel: fast
        modules: []
    additional-components: []

imagePullSecret: ""

testConfig:
  kebDeployment:
    useAnnotations: false
    weight: "2"

globalaccounts:
  enabled: false
  dryRun: true
  name: "kyma-environment-globalaccounts"

serviceBindingCleanup:
  enabled: false
  dryRun: true
  schedule: "0 2,14 * * *"
  requestTimeout: 2s
  requestRetries: 2

regionsSupportingMachine: |-

multipleContexts: false


plansConfiguration:
  sap-converged-cloud:
    regions:
      cf-eu20: [ "eu-de-1" ]
      cf-ap10: [ "ap-au-1" ]
      cf-us10: [ "na-us-1" ]
      cf-jp10: [ "ap-jp-1" ]
      cf-eu10: [ "eu-de-2" ]
      cf-us20: [ "na-us-2" ]
      cf-in30: [ "ap-ae-1" ]

  gcp,build-runtime-gcp:
    regions:
      cf-sa30:
        - "cf-sa30"
      default:
        - "europe-west3"
        - "asia-south1"
        - "us-central1"
        - "me-central2"
        - "asia-northeast2"
        - "me-west1"
        - "southamerica-east1"
        - "australia-southeast1"
        - "asia-northeast1"
        - "asia-southeast1"
        - "us-west1"
        - "us-east4"
        - "europe-west4"
  aws,build-runtime-aws:
    regions:
      cf-eu11: [ "eu-central-1" ]
      default: [ "eu-central-1", "eu-west-2", "ca-central-1", "sa-east-1", "us-east-1", "us-west-2", "ap-northeast-1", "ap-northeast-2", "ap-south-1", "ap-southeast-1", "ap-southeast-2" ]
  azure,build-runtime-azure,azure_lite:
    regions:
      cf-ch20: [ "switzerlandnorth" ]
      default: [ "eastus","centralus","westus2","uksouth","northeurope","westeurope","japaneast","southeastasia","australiaeast","brazilsouth","canadacentral" ]

providersCofiguration:
  aws:
    regions:
      eu-central-1:
        displayName: "eu-central-1 (Europe, Frankfurt)"
        zones: [ "a", "b", "c" ]
      eu-west-2:
        displayName: "eu-west-2 (Europe, London)"
        zones: [ "a", "b", "c" ]
      ca-central-1:
        displayName: "ca-central-1 (Canada, Montreal)"
        zones: [ "a", "b", "d" ]
      sa-east-1:
        displayName: "sa-east-1 (Brazil, São Paulo)"
        zones: [ "a", "b", "c" ]
      us-east-1:
        displayName: "us-east-1 (US East, N. Virginia)"
        zones: [ "a", "b", "c", "d", "f" ]
      us-west-2:
        displayName: "us-west-2 (US West, Oregon)"
        zones: [ "a", "b", "c", "d" ]
      ap-northeast-1:
        displayName: "ap-northeast-1 (Asia Pacific, Tokyo)"
        zones: [ "a", "b", "c" ]
      ap-northeast-2:
        displayName: "ap-northeast-2 (Asia Pacific, Seoul)"
        zones: [ "a", "b", "c" ]
      ap-south-1:
        displayName: "ap-south-1 (Asia Pacific, Mumbai)"
        zones: [ "a", "b", "c" ]
      ap-southeast-1:
        displayName: "ap-southeast-1 (Asia Pacific, Singapore)"
        zones: [ "a", "b", "c" ]
      ap-southeast-2:
        displayName: "ap-southeast-2 (Asia Pacific, Sydney)"
        zones: [ "a", "b", "c" ]
  azure:
    regions:
      eastus:
        displayName: "eastus (US East, VA)"
        zones: [ "1", "2", "3" ]
      centralus:
        displayName: "centralus (US Central, IA)"
        zones: [ "1", "2", "3" ]
      westus2:
        displayName: "westus2 (US West, WA)"
        zones: [ "1", "2", "3" ]
      uksouth:
        displayName: "uksouth (UK South, London)"
        zones: [ "1", "2", "3" ]
      northeurope:
        displayName: "northeurope (Europe, Ireland)"
        zones: [ "1", "2", "3" ]
      westeurope:
        displayName: "westeurope (Europe, Netherlands)"
        zones: [ "1", "2", "3" ]
      japaneast:
        displayName: "japaneast (Japan, Tokyo)"
        zones: [ "1", "2", "3" ]
      southeastasia:
        displayName: "southeastasia (Asia Pacific, Singapore)"
        zones: [ "1", "2", "3" ]
      australiaeast:
        displayName: "australiaeast (Australia, Sydney)"
        zones: [ "1", "2", "3" ]
      brazilsouth:
        displayName: "brazilsouth (Brazil, São Paulo)"
        zones: [ "1", "2", "3" ]
      canadacentral:
        displayName: "canadacentral (Canada, Toronto)"
        zones: [ "1", "2", "3" ]
      switzerlandnorth:
        displayName: "switzerlandnorth (Switzerland, Zurich)"
        zones: [ "1", "2", "3" ]
  gcp:
    regions:
      europe-west3:
        displayName: "europe-west3 (Europe, Frankfurt)"
        zones: [ "a", "b", "c" ]
      asia-south1:
        displayName: "asia-south1 (India, Mumbai)"
        zones: [ "a", "b", "c" ]
      us-central1:
        displayName: "us-central1 (US Central, IA)"
        zones: [ "a", "b", "c" ]
      me-central2:
        displayName: "me-central2 (KSA, Dammam)"
        zones: [ "a", "b", "c" ]
      asia-northeast2:
        displayName: "asia-northeast2 (Japan, Osaka)"
        zones: [ "a", "b", "c" ]
      me-west1:
        displayName: "me-west1 (Israel, Tel Aviv)"
        zones: [ "a", "b", "c" ]
      southamerica-east1:
        displayName: "southamerica-east1 (Brazil, São Paulo)"
        zones: [ "a", "b", "c" ]
      australia-southeast1:
        displayName: "australia-southeast1 (Australia, Sydney)"
        zones: [ "a", "b", "c" ]
      asia-northeast1:
        displayName: "asia-northeast1 (Japan, Tokyo)"
        zones: [ "a", "b", "c" ]
      asia-southeast1:
        displayName: "asia-southeast1 (Singapore, Jurong West)"
        zones: [ "a", "b", "c" ]

      us-west1:
        displayName: "us-west1 (North America, Oregon)"
        zones: [ "a", "b", "c" ]
      us-east4:
        displayName: "us-east4 (North America, Virginia)"
        zones: [ "a", "b", "c" ]
      europe-west4:
        displayName: "europe-west4 (Europe, Netherlands)"
        zones: [ "a", "b", "c" ]
  sap-converged-cloud:
    regions:
      eu-de-1:
        displayName: "eu-de-1"
        zones: [ "a", "b", "d" ]
      eu-de-2:
        displayName: "eu-de-2"
        zones: [ "a", "b" ]
      ap-au-1:
        displayName: "ap-au-1"
        zones: [ "a", "b" ]
      na-us-1:
        displayName: "na-us-1"
        zones: [ "a", "b", "d" ]
      na-us-2:
        displayName: "na-us-2"
        zones: [ "a", "b" ]
      ap-jp-1:
        displayName: "ap-jp-1"
        zones: [ "a" ]
      ap-ae-1:
        displayName: "ap-ae-1"
        zones: [ "a" ]
