apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: website
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: website
  mtls:
    mode: PERMISSIVE
