apiVersion: v1
kind: Secret
metadata:
  name: website-oauth2-proxy
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  cookie-secret: {{ .Values.oauth2Proxy.cookieSecret | required "Please specify .Values.oauth2Proxy.cookieSecret" | quote }}
