apiVersion: v1
kind: Service
metadata:
  name: kyma-environment-broker-nodeport
  namespace: kcp-system
spec:
  selector:
    app.kubernetes.io/instance: kcp
    app.kubernetes.io/name: kyma-environment-broker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort