{{ if .Values.globalaccounts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kyma-environment-globalaccounts"
  namespace: kcp-system
  labels:
    app.kubernetes.io/name: kyma-environment-globalaccounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kyma-environment-globalaccounts
  template:
    metadata:
      name: kyma-environment-globalaccounts
      labels:
        app.kubernetes.io/name: kyma-environment-globalaccounts
    spec:
      serviceAccountName: kcp-kyma-environment-broker
      securityContext:
        runAsUser: 2000
      restartPolicy: Always
      containers:
        - name: kyma-environment-globalaccounts
          command: ["/bin/main"]
          image: europe-docker.pkg.dev/kyma-project/prod/kyma-environment-globalaccounts:1.0.0
          imagePullPolicy: Always
          env:
            - name: APP_DATABASE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: kcp-storage-client-secret
                  key: secretKey
                  optional: true
            - name: APP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: postgresql-broker-username
                  name: kcp-postgresql
            - name: APP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-broker-password
                  name: kcp-postgresql
            - name: APP_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  key: postgresql-serviceName
                  name: kcp-postgresql
            - name: APP_DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  key: postgresql-servicePort
                  name: kcp-postgresql
            - name: APP_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: postgresql-broker-db-name
                  name: kcp-postgresql
            - name: APP_DATABASE_SSLMODE
              valueFrom:
                secretKeyRef:
                  key: postgresql-sslMode
                  name: kcp-postgresql
            - name: APP_DATABASE_SSLROOTCERT
              value: /secrets/cloudsql-sslrootcert/server-ca.pem
        - name: cloudsql-proxy
          image: ${SCRIPT_CLOUDSQL_PROXY_IMAGE}
          imagePullPolicy: IfNotPresent
          command: ${SCRIPT_CLOUDSQL_PROXY_COMMAND} # set by script
{{ end }}