{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.analytics.name }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  cookie-secret: {{ .Values.analytics.oauth2Proxy.cookieSecret | required "Please specify .Values.analytics.oauth2Proxy.cookieSecret" | quote }}
  client-secret: {{ .Values.analytics.oauth2Proxy.clientSecret | required "Please specify .Values.analytics.oauth2Proxy.clientSecret" | quote }}
{{- end }}
