{{- if and .Values.global.secrets.enabled (eq .Values.global.secrets.mechanism "secrets") }}
{{- if eq .Values.manageSecrets true }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.edp.secretName }}"
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  secret: {{ .Values.edp.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cis.v1.secretName | required "please specify .Values.cis.v1.secretName" | quote }}
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.v1.id | required "please specify .Values.cis.v1.id" | b64enc | quote }}
  secret: {{ .Values.cis.v1.secret | required "please specify .Values.cis.v1.secret" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cis.v2.secretName | required "Please specify .Values.cis.v2.secretName" | quote}}
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.v2.id | required "please specify .Values.cis.v2.id" | b64enc | quote }}
  secret: {{ .Values.cis.v2.secret | required "please specify .Values.cis.v2.secret" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cis.accounts.secretName | required "please specify .Values.cis.accounts.secretName" | quote }}
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.accounts.id | required "please specify .Values.cis.accounts.id" | b64enc | quote }}
  secret: {{ .Values.cis.accounts.secret | required "please specify .Values.cis.accounts.secret " | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cis.entitlements.secretName | required "please specify .Values.cis.entitlements.secretName" | quote }}
  labels: {{ include "kyma-env-broker.labels" . | nindent 4 }}
type: Opaque
data:
  id: {{ .Values.cis.entitlements.id | required "please specify .Values.cis.entitlements.id" | b64enc | quote }}
  secret: {{ .Values.cis.entitlements.secret | required "please specify .Values.cis.entitlements.secret " | b64enc | quote }}
{{- end }}
{{- end }}