plansConfiguration:
  sap-converged-cloud:
    regularMachines:
      - "g_c2_m8"
      - "g_c4_m16"
      - "g_c6_m24"
      - "g_c8_m32"
      - "g_c12_m48"
      - "g_c16_m64"
      - "g_c32_m128"
      - "g_c64_m256"
    regions:
      cf-eu20:
        - eu-de-1
      cf-ap10:
        - ap-au-1
      cf-us10:
        - na-us-1
      cf-jp10:
        - ap-jp-1
      cf-eu10:
        - eu-de-2
      cf-us20:
        - na-us-2
      cf-in30:
        - ap-ae-1

  gcp,build-runtime-gcp:
    regularMachines:
      - "n2-standard-2"
      - "n2-standard-4"
      - "n2-standard-8"
      - "n2-standard-16"
      - "n2-standard-32"
      - "n2-standard-48"
      - "n2-standard-64"
    additionalMachines:
      - "c2d-highcpu-2"
      - "c2d-highcpu-4"
      - "c2d-highcpu-8"
      - "c2d-highcpu-16"
      - "c2d-highcpu-32"
      - "c2d-highcpu-56"
      - "g2-standard-4"
      - "g2-standard-8"
      - "g2-standard-12"
      - "g2-standard-16"
      - "g2-standard-24"
      - "g2-standard-32"
      - "g2-standard-48"
    regions:
      cf-sa30:
        - me-central2
      default:
        - europe-west3
        - asia-south1
        - us-central1
        - me-central2
        - asia-northeast2
        - me-west1
        - southamerica-east1
        - australia-southeast1
        - asia-northeast1
        - asia-southeast1
        - us-west1
        - us-east4
        - europe-west4
  preview,aws,build-runtime-aws:
    regularMachines:
      - "m6i.large"
      - "m6i.xlarge"
      - "m6i.2xlarge"
      - "m6i.4xlarge"
      - "m6i.8xlarge"
      - "m6i.12xlarge"
      - "m6i.16xlarge"
      - "m5.large"
      - "m5.xlarge"
      - "m5.2xlarge"
      - "m5.4xlarge"
      - "m5.8xlarge"
      - "m5.12xlarge"
      - "m5.16xlarge"
    additionalMachines:
      - "c7i.large"
      - "c7i.xlarge"
      - "c7i.2xlarge"
      - "c7i.4xlarge"
      - "c7i.8xlarge"
      - "c7i.12xlarge"
      - "c7i.16xlarge"
      - "g6.xlarge"
      - "g6.2xlarge"
      - "g6.4xlarge"
      - "g6.8xlarge"
      - "g6.12xlarge"
      - "g6.16xlarge"
      - "g4dn.xlarge"
      - "g4dn.2xlarge"
      - "g4dn.4xlarge"
      - "g4dn.8xlarge"
      - "g4dn.12xlarge"
      - "g4dn.16xlarge"
    regions:
      cf-eu11:
        - eu-central-1
      default:
        - eu-central-1
        - eu-west-2
        - ca-central-1
        - sa-east-1
        - us-east-1
        - us-west-2
        - ap-northeast-1
        - ap-northeast-2
        - ap-south-1
        - ap-southeast-1
        - ap-southeast-2
  azure,build-runtime-azure:
    regularMachines:
      - "Standard_D2s_v5"
      - "Standard_D4s_v5"
      - "Standard_D8s_v5"
      - "Standard_D16s_v5"
      - "Standard_D32s_v5"
      - "Standard_D48s_v5"
      - "Standard_D64s_v5"
      - "Standard_D4_v3"
      - "Standard_D8_v3"
      - "Standard_D16_v3"
      - "Standard_D32_v3"
      - "Standard_D48_v3"
      - "Standard_D64_v3"
    additionalMachines:
      - "Standard_F2s_v2"
      - "Standard_F4s_v2"
      - "Standard_F8s_v2"
      - "Standard_F16s_v2"
      - "Standard_F32s_v2"
      - "Standard_F48s_v2"
      - "Standard_F64s_v2"
      - "Standard_NC4as_T4_v3"
      - "Standard_NC8as_T4_v3"
      - "Standard_NC16as_T4_v3"
      - "Standard_NC64as_T4_v3"
    regions: &azure_regions
      cf-ch20:
        - switzerlandnorth
      default:
        - eastus
        - centralus
        - westus2
        - uksouth
        - northeurope
        - westeurope
        - japaneast
        - southeastasia
        - australiaeast
        - brazilsouth
        - canadacentral
  azure_lite:
    regions: *azure_regions
    regularMachines:
      - "Standard_D2s_v5"
      - "Standard_D4s_v5"
      - "Standard_D4_v3"

providersConfiguration:
  aws:
    machines:
      "m6i.large": "m6i.large (2vCPU, 8GB RAM)"
      "m6i.xlarge": "m6i.xlarge (4vCPU, 16GB RAM)"
      "m6i.2xlarge": "m6i.2xlarge (8vCPU, 32GB RAM)"
      "m6i.4xlarge": "m6i.4xlarge (16vCPU, 64GB RAM)"
      "m6i.8xlarge": "m6i.8xlarge (32vCPU, 128GB RAM)"
      "m6i.12xlarge": "m6i.12xlarge (48vCPU, 192GB RAM)"
      "m6i.16xlarge": "m6i.16xlarge (64vCPU, 256GB RAM)"
      "m5.large": "m5.large (2vCPU, 8GB RAM)"
      "m5.xlarge": "m5.xlarge (4vCPU, 16GB RAM)"
      "m5.2xlarge": "m5.2xlarge (8vCPU, 32GB RAM)"
      "m5.4xlarge": "m5.4xlarge (16vCPU, 64GB RAM)"
      "m5.8xlarge": "m5.8xlarge (32vCPU, 128GB RAM)"
      "m5.12xlarge": "m5.12xlarge (48vCPU, 192GB RAM)"
      "m5.16xlarge": "m5.16xlarge (64vCPU, 256GB RAM)"
      "c7i.large": "c7i.large (2vCPU, 4GB RAM)"
      "c7i.xlarge": "c7i.xlarge (4vCPU, 8GB RAM)"
      "c7i.2xlarge": "c7i.2xlarge (8vCPU, 16GB RAM)"
      "c7i.4xlarge": "c7i.4xlarge (16vCPU, 32GB RAM)"
      "c7i.8xlarge": "c7i.8xlarge (32vCPU, 64GB RAM)"
      "c7i.12xlarge": "c7i.12xlarge (48vCPU, 96GB RAM)"
      "c7i.16xlarge": "c7i.16xlarge (64vCPU, 128GB RAM)"
      "g6.xlarge": "g6.xlarge (1GPU, 4vCPU, 16GB RAM)*"
      "g6.2xlarge": "g6.2xlarge (1GPU, 8vCPU, 32GB RAM)*"
      "g6.4xlarge": "g6.4xlarge (1GPU, 16vCPU, 64GB RAM)*"
      "g6.8xlarge": "g6.8xlarge (1GPU, 32vCPU, 128GB RAM)*"
      "g6.12xlarge": "g6.12xlarge (4GPU, 48vCPU, 192GB RAM)*"
      "g6.16xlarge": "g6.16xlarge (1GPU, 64vCPU, 256GB RAM)*"
      "g4dn.xlarge": "g4dn.xlarge (1GPU, 4vCPU, 16GB RAM)*"
      "g4dn.2xlarge": "g4dn.2xlarge (1GPU, 8vCPU, 32GB RAM)*"
      "g4dn.4xlarge": "g4dn.4xlarge (1GPU, 16vCPU, 64GB RAM)*"
      "g4dn.8xlarge": "g4dn.8xlarge (1GPU, 32vCPU, 128GB RAM)*"
      "g4dn.12xlarge": "g4dn.12xlarge (4GPU, 48vCPU, 192GB RAM)*"
      "g4dn.16xlarge": "g4dn.16xlarge (1GPU, 64vCPU, 256GB RAM)*"
    regionsSupportingMachine:
      g6:
        us-west-2:
        eu-central-1: [ a, b ]
        ap-south-1: [ b ]
        us-east-1: [ a, b, c, d ]
      g4dn:
        eu-central-1:
        eu-west-2:
        us-east-1:
        ap-south-1:
        us-west-2: [ a, b, c ]
    regions:
      eu-central-1:
        displayName: eu-central-1 (Europe, Frankfurt)
        zones: [a, b, c]
      eu-west-2:
        displayName: eu-west-2 (Europe, London)
        zones: [a, b, c]
      ca-central-1:
        displayName: ca-central-1 (Canada, Montreal)
        zones: [a, b, d]
      sa-east-1:
        displayName: sa-east-1 (Brazil, São Paulo)
        zones: [a, b, c]
      us-east-1:
        displayName: us-east-1 (US East, N. Virginia)
        zones: [a, b, c, d, f]
      us-west-2:
        displayName: us-west-2 (US West, Oregon)
        zones: [a, b, c, d]
      ap-northeast-1:
        displayName: ap-northeast-1 (Asia Pacific, Tokyo)
        zones: [a, c, d]
      ap-northeast-2:
        displayName: ap-northeast-2 (Asia Pacific, Seoul)
        zones: [a, b, c]
      ap-south-1:
        displayName: ap-south-1 (Asia Pacific, Mumbai)
        zones: [a, b, c]
      ap-southeast-1:
        displayName: ap-southeast-1 (Asia Pacific, Singapore)
        zones: [a, b, c]
      ap-southeast-2:
        displayName: ap-southeast-2 (Asia Pacific, Sydney)
        zones: [a, b, c]
      eu-west-1: # used for trials
        displayName: eu-west-1 (Europe, Ireland)
        zones: [a]
  azure:
    machines:
      "Standard_D2s_v5": "Standard_D2s_v5 (2vCPU, 8GB RAM)"
      "Standard_D4s_v5": "Standard_D4s_v5 (4vCPU, 16GB RAM)"
      "Standard_D8s_v5": "Standard_D8s_v5 (8vCPU, 32GB RAM)"
      "Standard_D16s_v5": "Standard_D16s_v5 (16vCPU, 64GB RAM)"
      "Standard_D32s_v5": "Standard_D32s_v5 (32vCPU, 128GB RAM)"
      "Standard_D48s_v5": "Standard_D48s_v5 (48vCPU, 192GB RAM)"
      "Standard_D64s_v5": "Standard_D64s_v5 (64vCPU, 256GB RAM)"
      "Standard_D4_v3": "Standard_D4_v3 (4vCPU, 16GB RAM)"
      "Standard_D8_v3": "Standard_D8_v3 (8vCPU, 32GB RAM)"
      "Standard_D16_v3": "Standard_D16_v3 (16vCPU, 64GB RAM)"
      "Standard_D32_v3": "Standard_D32_v3 (32vCPU, 128GB RAM)"
      "Standard_D48_v3": "Standard_D48_v3 (48vCPU, 192GB RAM)"
      "Standard_D64_v3": "Standard_D64_v3 (64vCPU, 256GB RAM)"
      "Standard_F2s_v2": "Standard_F2s_v2 (2vCPU, 4GB RAM)"
      "Standard_F4s_v2": "Standard_F4s_v2 (4vCPU, 8GB RAM)"
      "Standard_F8s_v2": "Standard_F8s_v2 (8vCPU, 16GB RAM)"
      "Standard_F16s_v2": "Standard_F16s_v2 (16vCPU, 32GB RAM)"
      "Standard_F32s_v2": "Standard_F32s_v2 (32vCPU, 64GB RAM)"
      "Standard_F48s_v2": "Standard_F48s_v2 (48vCPU, 96GB RAM)"
      "Standard_F64s_v2": "Standard_F64s_v2 (64vCPU, 128GB RAM)"
      "Standard_NC4as_T4_v3": "Standard_NC4as_T4_v3 (1GPU, 4vCPU, 28GB RAM)*"
      "Standard_NC8as_T4_v3": "Standard_NC8as_T4_v3 (1GPU, 8vCPU, 56GB RAM)*"
      "Standard_NC16as_T4_v3": "Standard_NC16as_T4_v3 (1GPU, 16vCPU, 110GB RAM)*"
      "Standard_NC64as_T4_v3": "Standard_NC64as_T4_v3 (4GPU, 64vCPU, 440GB RAM)*"
    regionsSupportingMachine:
      Standard_NC:
        westus2:
        northeurope:
        westeurope:
    regions:
      eastus:
        displayName: eastus (US East, VA)
        zones: ['1', '2', '3']
      centralus:
        displayName: centralus (US Central, IA)
        zones: ['1', '2', '3']
      westus2:
        displayName: westus2 (US West, WA)
        zones: ['1', '2', '3']
      uksouth:
        displayName: uksouth (UK South, London)
        zones: ['1', '2', '3']
      northeurope:
        displayName: northeurope (Europe, Ireland)
        zones: ['1', '2', '3']
      westeurope:
        displayName: westeurope (Europe, Netherlands)
        zones: ['1', '2', '3']
      japaneast:
        displayName: japaneast (Japan, Tokyo)
        zones: ['1', '2', '3']
      southeastasia:
        displayName: southeastasia (Asia Pacific, Singapore)
        zones: ['1', '2', '3']
      australiaeast:
        displayName: australiaeast (Australia, Sydney)
        zones: ['1', '2', '3']
      brazilsouth:
        displayName: brazilsouth (Brazil, São Paulo)
        zones: ['1', '2', '3']
      canadacentral:
        displayName: canadacentral (Canada, Toronto)
        zones: ['1', '2', '3']
      switzerlandnorth:
        displayName: switzerlandnorth (Switzerland, Zurich)
        zones: ['1', '2', '3']
  gcp:
    machines:
      "n2-standard-2": "n2-standard-2 (2vCPU, 8GB RAM)"
      "n2-standard-4": "n2-standard-4 (4vCPU, 16GB RAM)"
      "n2-standard-8": "n2-standard-8 (8vCPU, 32GB RAM)"
      "n2-standard-16": "n2-standard-16 (16vCPU, 64GB RAM)"
      "n2-standard-32": "n2-standard-32 (32vCPU, 128GB RAM)"
      "n2-standard-48": "n2-standard-48 (48vCPU, 192GB RAM)"
      "n2-standard-64": "n2-standard-64 (64vCPU, 256GB RAM)"
      "c2d-highcpu-2": "c2d-highcpu-2 (2vCPU, 4GB RAM)"
      "c2d-highcpu-4": "c2d-highcpu-4 (4vCPU, 8GB RAM)"
      "c2d-highcpu-8": "c2d-highcpu-8 (8vCPU, 16GB RAM)"
      "c2d-highcpu-16": "c2d-highcpu-16 (16vCPU, 32GB RAM)"
      "c2d-highcpu-32": "c2d-highcpu-32 (32vCPU, 64GB RAM)"
      "c2d-highcpu-56": "c2d-highcpu-56 (56vCPU, 112GB RAM)"
      "g2-standard-4": "g2-standard-4 (1GPU, 4vCPU, 16GB RAM)*"
      "g2-standard-8": "g2-standard-8 (1GPU, 8vCPU, 32GB RAM)*"
      "g2-standard-12": "g2-standard-12 (1GPU, 12vCPU, 48GB RAM)*"
      "g2-standard-16": "g2-standard-16 (1GPU, 16vCPU, 64GB RAM)*"
      "g2-standard-24": "g2-standard-24 (2GPU, 24vCPU, 96GB RAM)*"
      "g2-standard-32": "g2-standard-32 (1GPU, 32vCPU, 128GB RAM)*"
      "g2-standard-48": "g2-standard-48 (4GPU, 48vCPU, 192GB RAM)*"
    regionsSupportingMachine:
      c2d-highcpu:
        europe-west3:
        asia-south1:
        us-central1:
        asia-southeast1:
        us-west1:
        us-east4:
        europe-west4:
      g2-standard:
        asia-south1:
        us-west1:
        us-central1:
        europe-west4:
        europe-west3: [ a, b ]
    regions:
      europe-west3:
        displayName: europe-west3 (Europe, Frankfurt)
        zones: [a, b, c]
      asia-south1:
        displayName: asia-south1 (India, Mumbai)
        zones: [a, b, c]
      us-central1:
        displayName: us-central1 (US Central, IA)
        zones: [a, b, c]
      me-central2:
        displayName: me-central2 (KSA, Dammam)
        zones: [a, b, c]
      asia-northeast2:
        displayName: asia-northeast2 (Japan, Osaka)
        zones: [a, b, c]
      me-west1:
        displayName: me-west1 (Israel, Tel Aviv)
        zones: [a, b, c]
      southamerica-east1:
        displayName: southamerica-east1 (Brazil, São Paulo)
        zones: [a, b, c]
      australia-southeast1:
        displayName: australia-southeast1 (Australia, Sydney)
        zones: [a, b, c]
      asia-northeast1:
        displayName: asia-northeast1 (Japan, Tokyo)
        zones: [a, b, c]
      asia-southeast1:
        displayName: asia-southeast1 (Singapore, Jurong West)
        zones: [a, b, c]
      us-west1:
        displayName: us-west1 (North America, Oregon)
        zones: [a, b, c]
      us-east4:
        displayName: us-east4 (North America, Virginia)
        zones: [a, b, c]
      europe-west4:
        displayName: europe-west4 (Europe, Netherlands)
        zones: [a, b, c]
  sap-converged-cloud:
    machines:
      "g_c2_m8": "g_c2_m8 (2vCPU, 8GB RAM)"
      "g_c4_m16": "g_c4_m16 (4vCPU, 16GB RAM)"
      "g_c6_m24": "g_c6_m24 (6vCPU, 24GB RAM)"
      "g_c8_m32": "g_c8_m32 (8vCPU, 32GB RAM)"
      "g_c12_m48": "g_c12_m48 (12vCPU, 48GB RAM)"
      "g_c16_m64": "g_c16_m64 (16vCPU, 64GB RAM)"
      "g_c32_m128": "g_c32_m128 (32vCPU, 128GB RAM)"
      "g_c64_m256": "g_c64_m256 (64vCPU, 256GB RAM)"
    regions:
      eu-de-1:
        displayName: eu-de-1
        zones: [a, b, d]
      eu-de-2:
        displayName: eu-de-2
        zones: [a, b]
      ap-au-1:
        displayName: ap-au-1
        zones: [a, b]
      na-us-1:
        displayName: na-us-1
        zones: [a, b, d]
      na-us-2:
        displayName: na-us-2
        zones: [a, b]
      ap-jp-1:
        displayName: ap-jp-1
        zones: [a]
      ap-ae-1:
        displayName: ap-ae-1
        zones: [a, b]