{
 "title": "KCP / Kyma Environment Broker / Runtime Business Metrics",
 "tags": [
  "kyma-environment-broker",
  "kcp"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "global_account_id",
    "query": {
     "query": "label_values(kcp_keb_v2_global_account_id_instances_total, global_account_id)"
    }
   },
   {
    "name": "sub_account_id",
    "query": {
     "query": "label_values(kcp_keb_v2_sub_account_id_instances_total, sub_account_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of instances (without suspended)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kcp_keb_v2_instances_total{})"
    }
   ]
  },
  { "title": "Global Accounts instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total number of Global Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kcp_keb_v2_global_account_id_instances_total{})"
    }
   ]
  },
  {
   "title": "Top 16 number of instances per Global Account ID",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(16, kcp_keb_v2_global_account_id_instances_total{})",
     "legendFormat": "{{global_account_id}}"
    }
   ]
  },
  {
   "title": "Average number of instances per Global Account",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kcp_keb_v2_global_account_id_instances_total{})"
    }
   ]
  },
  {
   "title": "Number of instances per Global Account ID $global_account_id",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kcp_keb_v2_global_account_id_instances_total{global_account_id=\"$global_account_id\"})",
     "legendFormat": "Number of instances per Global Account ID $global_account_id"
    }
   ]
  },
  { "title": "Subaccounts instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Total number of Subaccounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kcp_keb_v2_sub_account_id_instances_total{})"
    }
   ]
  },
  {
   "title": "Top 16 number of instances per Subaccount ID",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(16, kcp_keb_v2_sub_account_id_instances_total{})",
     "legendFormat": "{{sub_account_id}}"
    }
   ]
  },
  {
   "title": "Average number of instances per Subaccount",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kcp_keb_v2_sub_account_id_instances_total{})"
    }
   ]
  },
  {
   "title": "Number of instances per Subaccount ID $sub_account_id",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kcp_keb_v2_sub_account_id_instances_total{sub_account_id=\"$sub_account_id\"})",
     "legendFormat": "Number of instances per Subaccount ID $sub_account_id"
    }
   ]
  }
 ]
}