.PHONY: lint
lint:
	npm install
	npm run lint

.PHONY: lint-fix
lint-fix:
	npm install
	npm run lint-fix

.PHONY: keb-endpoints
keb-endpoints:
	npm install
	npm run keb-endpoints-test

.PHONY: skr
skr:
	npm install
	npm run skr-test
	