name: "Create and promote release"
run-name: Create and promote release ${{ inputs.name }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Create release'
        default: ""
        required: true

jobs:
  create-release:
    name: Create release
    uses: "./.github/workflows/create-release.yaml"
    with:
      name: ${{ inputs.name }}
      skip-sec-file-and-chart-bump: false
      dry-run: false
    secrets: inherit

  promote:
    name: Promote
    needs: create-release
    uses: "./.github/workflows/promote-keb-to-dev.yaml"
    with:
      releaseTag: ${{ inputs.name }}
    secrets: inherit
