name: All checks passed
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
    - edited
    - labeled
    - unlabeled
      
jobs:
  checks-passed:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
    steps:
      - name: Check if draft
        if: ${{ github.event.pull_request.draft }}
        run: | 
          echo "Draft PRs are not checked"
          exit 1
      - name: Check if author is kyma-gopher-bot
        if: ${{ github.event.pull_request.user.login == 'kyma-gopher-bot' }}
        run: | 
          echo "PRs from kyma-gopher-bot are automatically green"
          exit 0
      - uses: wechuli/allcheckspassed@2e5e8bbc775f5680ed5d02e3a22e2fc7219792ac
        if: ${{ github.event.pull_request.user.login != 'kyma-gopher-bot' }}
        with:
          delay: '1'
          retries: '15'
          polling_interval: '1'
          checks_exclude: 'markdown-link-check,enable-auto-merge,run-govulncheck,scan'
          verbose: true
