name: pull-build-images

on:
   pull_request_target:
      types: [ opened, synchronize, reopened, ready_for_review ]
      paths-ignore:
         - "**.md"
         - "sec-scanners-config.yaml"

permissions:
   id-token: write
   contents: read
jobs:
   kyma-environment-broker-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with: 
      name:  kyma-environment-broker
      dockerfile: Dockerfile.keb
      context: .

   archiver-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-archiver-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=archiver

   environments-cleanup-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environments-cleanup-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=environmentscleanup

   deprovision-retrigger-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-deprovision-retrigger-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=deprovisionretrigger

   expirator-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-expirator-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=expirator

   runtime-reconciler-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-runtime-reconciler
         dockerfile: Dockerfile.runtimereconciler
         context: .
         build-args: BIN=runtime-reconciler

   subaccount-cleanup-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-subaccount-cleanup-job
         dockerfile: Dockerfile.job
         context: .
         build-args: BIN=accountcleanup

   subaccount-sync-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-subaccount-sync
         dockerfile: Dockerfile.subaccountsync
         context: .
         build-args: BIN=subaccount-sync

   globalaccounts-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with: 
         name: kyma-environment-globalaccounts
         dockerfile: Dockerfile.globalaccounts
         context: .
         build-args: BIN=globalaccounts

   schema-migrator-image:
      uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
      with:
         name: kyma-environment-broker-schema-migrator
         dockerfile: Dockerfile.schemamigrator
         context: .
