name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    # Trigger for Pull Request
    branches: [ "main" ]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Depracated
        shell: bash
        run: echo "This action is depracated, due to use Verify KEB / run-go-tests / build action instead."