name: Validate and deploy keb helm chart 

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  run-keb-chart-tests:
    uses: "./.github/workflows/run-keb-chart-tests-reusable.yaml"
    if: ${{ !github.event.pull_request.draft }}
    with:
      last-k3s-versions: 3

