apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  labels:
    hyperscalerType: alicloud
  name: alicloud-secret-binding
  namespace: garden-kyma-dev
provider:
  type: alicloud
secretRef:
  name: alicloud-secret
  namespace: garden-kyma-dev
